#!/usr/bin/env python3
# Bubbler - Copyright (C) 2026 InPoint Automation Sp. z o.o.
# Licensed under the GNU General Public License v3 or later; see LICENSE.
#
# Regenerate bubbler/sheet_template.py from xlsx template.
import base64
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))          # template/
_REPO = os.path.dirname(_HERE)                              # repo root
src = (sys.argv[1] if len(sys.argv) > 1
       else os.path.join(_HERE, "inspection_sheet_template.xlsx"))
out = os.path.join(_REPO, "bubbler", "sheet_template.py")

b64 = base64.b64encode(open(src, "rb").read()).decode("ascii")
with open(out, "w", encoding="utf-8") as f:
    f.write("# generated by template/make_template_module.py - do not edit\n")
    f.write('TEMPLATE_B64 = """\\\n')
    for i in range(0, len(b64), 76):
        f.write(b64[i:i + 76] + "\n")
    f.write('"""\n')
print("%s written (%d KB source)" % (out, len(b64) // 1024))
